@startuml
participant main
participant gps_module
participant tempsensors

main -> gps_module: more then 3 sat?

main -> main: wait 700ms
main -> tempsensor: wake
main -> main: wait 260ms
main -> tempsensor: read temp
main -> currentsensor: read current
main -> main: read voltage

alt pps based
   gps_module -> main: yes
   gps_module -> main: pps_signal

else timer based
   gps_module -> main: no
   main -> main: wait for 1s timer
end
main -> loRa: send Protcol
@enduml